name: check-capital-ubuntu-chrome
on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * 4'

jobs:
  tests:
    name: I. Building environment, testing the capital.com website and saving artifacts
    runs-on: ubuntu-latest
    steps:
      - name: 1. Check out this repo
        uses: actions/checkout@v3

      - name: 2.1. Install Python
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 2.2. Check Python
        if: always()
        run: python3 --version

      - name: 3.1. Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      
      - name: 3.2. Check brew
        if: always()
        run: 
#           /home/linuxbrew/.linuxbrew/bin/brew shellenv
          brew --version

      - name: 3.3. Install Neofetch
        if: always()
        run: brew install neofetch

      - name: 4. install Poetry
        if: always()
        run: pip install poetry

      - name: 5. install dependencies
        if: always()
        run: poetry update

      - name: 6. Run hwinfo.py
        run: poetry run python3 tests/hwinfo.py

      - name: 7. Run hwinfo.py
        run: poetry run python3 tests/hwinfo.py > tests/hwinfo.txt

      - name: 8. Run pytest
        if: always()
        run: poetry run pytest -n logical
        continue-on-error: true

      - name: 9. Upload artifact "results"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/

      - name: 10. Upload artifact "allure-results"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
          retention-days: 10

      - name: 11. Upload artifact "hwinfo.txt"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: hwinfo.txt
          path: tests/hwinfo.txt

  generate_report:
    name: II. Generate & Deploy Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]
    steps:
      - name: 1. Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 2. Download Artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: allure-results
          path: allure-results

      - name: 3. Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          ref: gh-pages
          path: gh-pages
          keep_reports: 15

      - name: 4. Deploy allure_report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: ./allure-history

  send_message:
    name: III. Send massage to Telegram about the end of process
    runs-on: ubuntu-latest
    if: always()
    needs: [ generate_report ]
    steps:
      - name: 1. Get access to github repository
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 2. Download Artifacts "hwinfo.txt"
        uses: actions/download-artifact@v3
        if: always()
        id: download
        continue-on-error: true
        with:
          name: hwinfo.txt
          path: tests/

      - name: 3. Send telegram message on push
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
#           disable_web_page_preview: true
          document: tests/hwinfo.txt
          message: |
            Message from Github CI Actions

            Testing of the "Capital.com" web application in the "Ubuntu/Chrome" environment is completed!

            See allure-result testing: https://${{ github.actor }}.github.io/TestCapitalCom/
#             Tests Repository: https://github.com/${{ github.repository }}
