name: Testing Capital.com and deploy test results. Env. MacOS, Safary
on:
  workflow_dispatch:
  schedule:
    - cron: '00 12 * * 5'

jobs:
  tests:
    name: Test & upload Artifacts
    runs-on: macos-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: install Python
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install Poetry
        if: always()
        run: pip install poetry

      - name: install dependencies
        if: always()
        run: poetry update

      - name: Run pytest
        if: always()
        run: poetry run pytest -v
        continue-on-error: true

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/

      - name: Upload artifact
        if: always()
#         uses: actions/upload-artifact@master
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
          retention-days: 10

  generate_report:
    name: Allure report & notification
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]
    steps:
      - name: Download Artifacts 🔻
        uses: actions/download-artifact@v3
        id: download
        with:
          name: allure-results
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
#           allure_report: ${{ github.run_number }}
#           allure_history: /allure-history
          allure_report: allure-report
          allure_history: allure-history
          gh_pages: gh-pages
          ref: gh-pages
          path: gh-pages
          keep_reports: 15

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure_report
          path: allure_report/

      - name: Deploy allure_report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  send_message:
    name: Allure report & notification
    runs-on: ubuntu-latest
    if: always()
    needs: [ generate_report ]
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Message from ${{ github.actor }}

            Testing of the web application "Capital.com" in the "MacOS-11/Safari-latest" environment is completed!

            See allure-result testing: https://${{ github.actor }}.github.io/TestCapitalCom/

            Tests Repository: https://github.com/${{ github.repository }}
