name: push-check-capital
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 4'

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Setup Node.JS V16  
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Chrome
        if: always()
        uses: browser-actions/setup-chrome@latest
      - name: check Chrome version
        run: chrome --version

      - name: Setup Firefox
        if: always()
        uses: browser-actions/setup-firefox@latest
      - name: check Firefox version
        run: firefox --version

      - name: Setup Edge
        uses: browser-actions/setup-edge@latest

      - name: install Python
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install Poetry
        if: always()
        run: pip install poetry

      - name: install dependencies
        if: always()
        run: poetry update

      - name: Run pytest
        if: always()
        run: poetry run pytest -v
        continue-on-error: true

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/

      - name: Get Allure history
        if: always()
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 15

      - name: Deploy allure-report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }}

            Testing completed!

            Tests Repository: https://github.com/${{ github.repository }}

            See result testing: https://${{ github.actor }}.github.io/${{ github.repository }}/deployments
            
#             See result testing: https://${{ github.actor }}.github.io/${{ github.repository }}/${{github.sha}}/#
