name: push-check-capital
on: workflow_dispatch
jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out this repo
        uses: actions/checkout@v3
      
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: check Chrome version
        run: chrome --version
      
      - name: install Poetry
        run: pip install poetry
      - name: install dependencies
        run: poetry update
      
      - name: Run the pytest
        run: poetry run pytest -v

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: |
            report/
            !rport/*.png

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 15

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
